server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 512

management:
  endpoint:
    health:
      show-details: always
    info:
      git:
        mode: full
  endpoints:
    web:
      exposure:
        include: "beans,flyway,health,info,scheduledtasks"

spring:
  main:
    lazy-initialization: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
      ACCEPT_EMPTY_STRING_AS_NULL_OBJECT: true
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true
      ACCEPT_CASE_INSENSITIVE_PROPERTIES: true
    default-property-inclusion: non_null

  mail:
    default-encoding: UTF-8
    host: localhost
    port: 2525
    username: username
    password: secret
    properties:
      mail:
        debug: true
        smtp:
          from: no-reply@wutsi.com
          auth: true
          starttls:
            enable: true
    test-connection: false

wutsi:
  client-id: marketplace-manager
  application:
    name: marketplace-manager
    asset-url: https://int-wutsi.s3.amazonaws.com/static/wutsi-assets
    webapp-url: https://wutsi-web-test.herokuapp.com
    website-url: https://www.wusti.app
    email:
      welcome:
        debug: true
  platform:
    security:
      type: jwt
      public-endpoints:
        - "GET /v1/categories/{id}"
        - "GET /v1/categories/search"
        - "GET /v1/offers/{id}"
        - "POST /v1/offers/search"
        - "GET /v1/products/{id}"
        - "POST /v1/products/search"
        - "GET /v1/stores/{id}"
        - "GET /v1/fundraisings/{id}"
    cache:
      name: ${wutsi.application.name}
      type: local
    messaging:
      sms:
        type: none
      push:
        type: none
      url-shortener:
        type: none
      whatsapp:
        type: none
    stream:
      name: ${wutsi.application.name}
      type: local
    tracing:
      client-id: ${wutsi.application.name}
      device-id-provider:
        type: header

logging:
  level:
    root: INFO
    com.wutsi.marketplace.manager: DEBUG
  pattern:
    console: "%d type=%level logger=%class{20} thread=%thread %m%n"
    file: "%d type=%level logger=%class{20} thread=%thread %m%n"


